version: '2'
services:
 transmission:
  image: sebienfait/transmission-openvpn
  privileged: true
  restart: always
  ports:
    - "9091:9091"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /your/storage/path/:/data
  environment:
    - OPENVPN_PROVIDER=vpntunnel
    - OPENVPN_USERNAME=sebienfait
    - OPENVPN_PASSWORD=password
    - OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60"
    - LOCAL_NETWORK=192.168.1.0/24

 proxy:
  image: sebienfait/transmission-openvpn-proxy
  links:
    - transmission
  ports:
    - 8080:8080
  volumes:
    - /etc/localtime:/etc/localtime:ro
